import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import Link from "next/link";


const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>SuperSonicAI</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="header flex w-full justify-between p-8">
        <Link href={"/"}>
          <h1 className="text-4xl font-bold cursor-pointer text-purple-800">SuperSonicAI</h1>
        </Link>
        <div className="gap-2 flex flex-row">
          <button className=" rounded bg-slate-700 p-2">Our Story</button>
          <a target="_blank" href="https://git.cs.vt.edu/dmath010/supersonicai" rel="noopener noreferrer">
            <button className=" rounded bg-slate-700 p-2">View the Source Code</button>
          </a>
        </div>
      </header>
      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <h1 className="text-purple-800 text-2xl">Welcome to SuperSonicAI</h1>
        <p className="">Content coming soon!</p>

      </main>
    </>
  );
};

export default Home;
